"""Initial schema with UUIDs

Revision ID: 2028fc6c2de0
Revises: 
Create Date: 2026-05-02 22:00:45.567116

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2028fc6c2de0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_name'), 'workspace', ['name'], unique=False)
    op.create_table('credential',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('auth_type', sa.Enum('NONE', 'BASIC', 'SASL_JAAS', 'AWS_IAM', name='authtype'), nullable=True),
    sa.Column('encrypted_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sourceconnection',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('engine', sa.Enum('POSTGRESQL', 'MYSQL', name='sourceengine'), nullable=True),
    sa.Column('host', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('database_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('engine_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('credential_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['credential.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('targetconnection',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('engine', sa.Enum('KAFKA', name='targetengine'), nullable=True),
    sa.Column('engine_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('credential_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['credential.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_connection_id', sa.Uuid(), nullable=False),
    sa.Column('target_connection_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('STOPPED', 'RUNNING', 'FAILED', 'DEPLOYING', 'STOPPING', name='pipelinestatus'), nullable=True),
    sa.Column('current_deployment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('snapshot_mode', sa.Enum('INITIAL', 'SCHEMA_ONLY', 'NEVER', 'ALWAYS', name='snapshotmode'), nullable=True),
    sa.Column('key_format', sa.Enum('JSON', 'AVRO', 'PROTOBUF', name='formattype'), nullable=True),
    sa.Column('value_format', sa.Enum('JSON', 'AVRO', 'PROTOBUF', name='formattype'), nullable=True),
    sa.Column('advanced_properties', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_connection_id'], ['sourceconnection.id'], ),
    sa.ForeignKeyConstraint(['target_connection_id'], ['targetconnection.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipelinetablefilter',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pipeline_id', sa.Uuid(), nullable=False),
    sa.Column('schema_pattern', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('table_pattern', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_included', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipelinetransform',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pipeline_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transform_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('configuration', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('execution_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipelinetransform')
    op.drop_table('pipelinetablefilter')
    op.drop_table('pipeline')
    op.drop_table('targetconnection')
    op.drop_table('sourceconnection')
    op.drop_table('credential')
    op.drop_index(op.f('ix_workspace_name'), table_name='workspace')
    op.drop_table('workspace')
    # ### end Alembic commands ###
